name: 🚀 Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout GitHub Repo
        uses: actions/checkout@v3

      - name: 🚀 Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "wiafe1713@gmail.com"
          git config --global user.name "Beno28"

          echo "🔗 Cloning Hugging Face Space repo..."
          git clone https://huggingface.co/spaces/Beno28/GHASpecbot1.0 hf_space

          echo "📦 Copying files to Hugging Face repo..."
          shopt -s extglob
          cp -r !(hf_space) hf_space/
          cp -r .streamlit hf_space/ || true  # In case you use .streamlit folder
          cd hf_space

          echo "📌 Committing and pushing to HF Space..."
          git add .
          git commit -m '🚀 Automated deploy from GitHub Actions' || echo "No changes to commit"
          git push https://Beno28:${HF_TOKEN}@huggingface.co/spaces/Beno28/GHASpecbot1.0 main
