name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "wiafe1713@gmail.com"
          git config --global user.name "Beno28"
          
          git clone https://Beno28:$HF_TOKEN@huggingface.co/spaces/Beno28/GHASpecbot1.0 hf_space
          cp -r * hf_space/
          cd hf_space
          
          git add .
          git commit -m "Deploying to Hugging Face" || echo "Nothing to commit"
          git push origin main
