name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: IngBeno28/GHA--Specbot-1.2
        huggingface_repo_id: Beno28/GHASpecbot1.0
        repo_type: space
        space_sdk: streamlit
        hf_token: ${{ secrets.HF_TOKEN }}
